name: Feature request
description: Request a new feature.
labels: ["T-Enhancement"]
body:
  - type: textarea
    attributes:
      label: Description of feature.
    validations:
      required: true
