"""Add support for tracking number of Git pulls on package repositories

Revision ID: 30382babf339
Revises: 725c0156a71b
Create Date: 2022-05-22 21:39:19.521123

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30382babf339'
down_revision = '725c0156a71b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PackageBases', sa.Column('NumGitPulls', mysql.BIGINT(unsigned=True), nullable=False))
    op.alter_column('PackageKeywords', 'PackageBaseID',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=True)
    op.alter_column('PackageLicenses', 'PackageID',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=True)
    op.alter_column('PackageLicenses', 'LicenseID',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PackageLicenses', 'LicenseID',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=False)
    op.alter_column('PackageLicenses', 'PackageID',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=False)
    op.alter_column('PackageKeywords', 'PackageBaseID',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=False)
    op.drop_column('PackageBases', 'NumGitPulls')
    # ### end Alembic commands ###
