"""Removed Groups table

Revision ID: 5fe6830206a3
Revises: d4fec0a09ebd
Create Date: 2022-03-20 23:28:23.413636

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "5fe6830206a3"
down_revision = "d4fec0a09ebd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("PackageGroups")
    op.drop_index("Name", table_name="Groups")
    op.drop_table("Groups")
    op.alter_column(
        "PackageKeywords",
        "PackageBaseID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=True,
    )
    op.alter_column(
        "PackageLicenses",
        "PackageID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=True,
    )
    op.alter_column(
        "PackageLicenses",
        "LicenseID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "PackageLicenses",
        "LicenseID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=False,
    )
    op.alter_column(
        "PackageLicenses",
        "PackageID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=False,
    )
    op.alter_column(
        "PackageKeywords",
        "PackageBaseID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=False,
    )
    op.create_table(
        "Groups",
        sa.Column(
            "ID",
            mysql.INTEGER(display_width=10, unsigned=True),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("Name", mysql.VARCHAR(length=255), nullable=False),
        sa.PrimaryKeyConstraint("ID"),
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("Name", "Groups", ["Name"], unique=False)
    op.create_table(
        "PackageGroups",
        sa.Column(
            "PackageID",
            mysql.INTEGER(display_width=10, unsigned=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "GroupID",
            mysql.INTEGER(display_width=10, unsigned=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["GroupID"], ["Groups.ID"], name="PackageGroups_ibfk_2", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["PackageID"],
            ["Packages.ID"],
            name="PackageGroups_ibfk_1",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("PackageID", "GroupID"),
        mysql_collate="utf8mb4_unicode_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
