"""Add support for distro extensions on package dependencies, relations, and sources

Revision ID: 725c0156a71b
Revises: 8815353c32e5
Create Date: 2022-04-08 00:47:47.567361

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "725c0156a71b"
down_revision = "8815353c32e5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "PackageDepends", sa.Column("DepDist", sa.String(length=255), nullable=True)
    )
    op.alter_column(
        "PackageKeywords",
        "PackageBaseID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=True,
    )
    op.alter_column(
        "PackageLicenses",
        "PackageID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=True,
    )
    op.alter_column(
        "PackageLicenses",
        "LicenseID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=True,
    )
    op.add_column(
        "PackageRelations", sa.Column("RelDist", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "PackageSources", sa.Column("SourceDist", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("PackageSources", "SourceDist")
    op.drop_column("PackageRelations", "RelDist")
    op.alter_column(
        "PackageLicenses",
        "LicenseID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=False,
    )
    op.alter_column(
        "PackageLicenses",
        "PackageID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=False,
    )
    op.alter_column(
        "PackageKeywords",
        "PackageBaseID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=False,
    )
    op.drop_column("PackageDepends", "DepDist")
    # ### end Alembic commands ###
