"""Added support for Repology Out of Date notifications

Revision ID: d4fec0a09ebd
Revises: be7adae47ac3
Create Date: 2022-03-08 23:50:51.257935

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "d4fec0a09ebd"
down_revision = "be7adae47ac3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "PackageBases",
        sa.Column("RepologyCheck", mysql.TINYINT(unsigned=True), nullable=False),
    )
    op.alter_column(
        "PackageGroups",
        "PackageID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=True,
    )
    op.alter_column(
        "PackageGroups",
        "GroupID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=True,
    )
    op.alter_column(
        "PackageKeywords",
        "PackageBaseID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=True,
    )
    op.alter_column(
        "PackageLicenses",
        "PackageID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=True,
    )
    op.alter_column(
        "PackageLicenses",
        "LicenseID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "PackageLicenses",
        "LicenseID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=False,
    )
    op.alter_column(
        "PackageLicenses",
        "PackageID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=False,
    )
    op.alter_column(
        "PackageKeywords",
        "PackageBaseID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=False,
    )
    op.alter_column(
        "PackageGroups",
        "GroupID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=False,
    )
    op.alter_column(
        "PackageGroups",
        "PackageID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=False,
    )
    op.drop_column("PackageBases", "RepologyCheck")
    # ### end Alembic commands ###
